### ISSUE TITLE
ABI 1 demo broken on website

### ISSUE THREAD

**Issue by alexsb** [Caleydo/caleydo-vials#88]
http://vcglab.org/vials/caleydo-altsplice/index.html?file=data/abi1_bm_2k.json&exonLength=60

![image](https://cloud.githubusercontent.com/assets/2039375/8404415/19965904-1e4d-11e5-9b16-d6378f496ad6.png)

**Comment by alexsb** [comment]
It seems to affect all examples....

**Comment by alexsb** [comment]
![image](https://cloud.githubusercontent.com/assets/2039375/8404471/884f4f5e-1e4d-11e5-9795-04c44ee2cfa8.png)

Reads view is also affected

**Comment by bilalsal** [comment]
As I understand this was a caching problem and is now resolved
